CREATE TABLE events
(
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    text LONGTEXT NOT NULL,
    permission INT NOT NULL,
    datetime TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE groups
(
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    info LONGTEXT NOT NULL,
    parent_id INT DEFAULT 0 NOT NULL
);
CREATE TABLE students
(
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    user_id INT NOT NULL
);
CREATE TABLE students_groups
(
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    group_id INT NOT NULL,
    student_id INT NOT NULL
);
CREATE TABLE subjects
(
    id INT PRIMARY KEY NOT NULL,
    name VARCHAR(64) NOT NULL
);
CREATE TABLE teachers
(
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    uid INT NOT NULL
);
CREATE TABLE tokens
(
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    uid INT NOT NULL,
    token VARCHAR(32) NOT NULL
);
CREATE TABLE users
(
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    login VARCHAR(64) NOT NULL,
    passwd VARCHAR(32) NOT NULL,
    name VARCHAR(64) NOT NULL,
    middlename VARCHAR(64) NOT NULL,
    surname VARCHAR(64) NOT NULL,
    home VARCHAR(64) NOT NULL,
    level INT NOT NULL
);